-- Agenda inicial de WonderKids. Ejecutar en el SQL Editor de Supabase.
-- La migracion es idempotente para poder aplicarla sobre la base actual.

alter table public.pacientes
  add column if not exists padre_nombre text,
  add column if not exists padre_telefono text;

create table if not exists public.terapeutas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  especialidad text not null,
  email text,
  telefono text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sesiones (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  terapeuta_id bigint not null references public.terapeutas(id),
  fecha date not null,
  hora_inicio time not null,
  hora_fin time not null,
  tipo_sesion text not null default 'Sesion individual',
  estado text not null default 'programada' check (estado in ('programada', 'confirmada', 'realizada', 'cancelada', 'reprogramada')),
  estado_pago text not null default 'pendiente' check (estado_pago in ('pendiente', 'pagado', 'vencido', 'exonerado')),
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sesiones_fecha_idx on public.sesiones(fecha);
create index if not exists sesiones_paciente_idx on public.sesiones(paciente_id);
create index if not exists sesiones_terapeuta_idx on public.sesiones(terapeuta_id);

create or replace view public.v_agenda_pacientes as
select
  s.id,
  s.fecha,
  s.hora_inicio,
  s.hora_fin,
  s.tipo_sesion,
  s.estado,
  s.estado_pago,
  s.notas,
  p.id as paciente_id,
  p.nombre as paciente,
  p.padre_nombre,
  p.padre_telefono,
  t.id as terapeuta_id,
  t.nombre as terapeuta,
  t.especialidad
from public.sesiones s
join public.pacientes p on p.id = s.paciente_id
join public.terapeutas t on t.id = s.terapeuta_id;

create or replace view public.v_resumen_dashboard as
select
  (select count(*) from public.pacientes where coalesce(activo, true)) as pacientes_activos,
  (select count(*) from public.terapeutas where activo) as terapeutas_activos,
  (select count(*) from public.sesiones where fecha = current_date and estado <> 'cancelada') as citas_hoy,
  (select count(*) from public.sesiones where fecha = current_date and estado = 'realizada') as asistencias_hoy;
